In [1]:
import numpy as np


In [2]:
a = np.arange(5)
b = np.arange(5,10)
print(a)
print(b)

print(np.dstack((a,b)))

[0 1 2 3 4]
[5 6 7 8 9]
[[[0 5]
  [1 6]
  [2 7]
  [3 8]
  [4 9]]]


In [3]:
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)
print(a)
print(b)

print(np.dstack((a,b)))

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[[ 0  6]
  [ 1  7]
  [ 2  8]]

 [[ 3  9]
  [ 4 10]
  [ 5 11]]]


In [4]:
a = np.arange(18).reshape(2,3,3)
b = np.arange(18,36).reshape(2,3,3)
print(a)
print(b)

print(np.dstack((a,b)))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
[[[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[27 28 29]
  [30 31 32]
  [33 34 35]]]
[[[ 0  1  2 18 19 20]
  [ 3  4  5 21 22 23]
  [ 6  7  8 24 25 26]]

 [[ 9 10 11 27 28 29]
  [12 13 14 30 31 32]
  [15 16 17 33 34 35]]]
