# 17/12/2022


In [3]:
import numpy as np

In [4]:
arr = np.array([45,65,43,32,21,54,67,87,11,55,66,33])
# sorted_arr= np.sort(arr)
sorted_arr= np.sort(arr)[::-1]
sorted_arr1= -np.sort(-arr)
print(sorted_arr)
print(sorted_arr1)

[87 67 66 65 55 54 45 43 33 32 21 11]
[87 67 66 65 55 54 45 43 33 32 21 11]


In [15]:
a = np.arange(1,7).reshape(2,3)
print(a)
# print(np.insert(a,1,2,1))
print(np.insert(a,[1],[[1],[2]],axis=1))

[[1 2 3]
 [4 5 6]]
[[1 1 2 3]
 [4 2 5 6]]


In [17]:
a = np.arange(8).reshape(2, 4)
x = (1, 3)
print(a)
print(np.insert(a, x, 999, axis=1))


[[0 1 2 3]
 [4 5 6 7]]
[[  0 999   1   2 999   3]
 [  4 999   5   6 999   7]]


In [20]:
a = np.arange(5)
print(np.append(a,[1,2,3]))

[0 1 2 3 4 1 2 3]


In [29]:
b = np.arange(9).reshape(3,3)
print(b)
print(b.ndim)
# print(np.append(a,[10,11,12],axis=0))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
2


In [35]:
a = np.arange(6).reshape(2,3)
print(a)

print(np.delete(a,0,1))
print(np.delete(a,0,0))

[[0 1 2]
 [3 4 5]]
[[1 2]
 [4 5]]
[[3 4 5]]


In [40]:
a = np.arange(10).reshape(2,5)
print(a)

print(np.delete(a,np.s_[::2], 1))
# print(np.delete(a,0,0))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 3]
 [6 8]]


In [42]:
a = np.arange(8).reshape(2, 4)
x = (1, 3)
print(a)
print(np.delete(a, x, axis=1))


[[0 1 2 3]
 [4 5 6 7]]
[[0 2]
 [4 6]]


In [45]:
a = np.arange(8).reshape(2, 4)
b = np.arange(8,16).reshape(4,2)
print(a)
print(b)
print(np.dot(a,b))

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9]
 [10 11]
 [12 13]
 [14 15]]
[[ 76  82]
 [252 274]]


In [59]:
a = np.arange(4).reshape(2,2)
b = np.matrix(np.arange(8,12).reshape(2,2))
c = np.linalg.inv(a)
d = np.linalg.inv(b)
print(a)
print(b)
print(c)
print(d)
print("-------------------------------------------------------------------------------------------------------------------")
e = c.dot(a)
print(e)
f = b*d
print(f)

[[0 1]
 [2 3]]
[[ 8  9]
 [10 11]]
[[-1.5  0.5]
 [ 1.   0. ]]
[[-5.5  4.5]
 [ 5.  -4. ]]
-------------------------------------------------------------------------------------------------------------------
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


In [60]:
help(np.linalg.det) #determinant

Help on function det in module numpy.linalg:

det(a)
    Compute the determinant of an array.
    
    Parameters
    ----------
    a : (..., M, M) array_like
        Input array to compute determinants for.
    
    Returns
    -------
    det : (...) array_like
        Determinant of `a`.
    
    See Also
    --------
    slogdet : Another way to represent the determinant, more suitable
      for large matrices where underflow/overflow may occur.
    scipy.linalg.det : Similar function in SciPy.
    
    Notes
    -----
    
    .. versionadded:: 1.8.0
    
    Broadcasting rules apply, see the `numpy.linalg` documentation for
    details.
    
    The determinant is computed via LU factorization using the LAPACK
    routine ``z/dgetrf``.
    
    Examples
    --------
    The determinant of a 2-D array [[a, b], [c, d]] is ad - bc:
    
    >>> a = np.array([[1, 2], [3, 4]])
    >>> np.linalg.det(a)
    -2.0 # may vary
    
    Computing determinants for a stack of matrices:
    
 

In [61]:
a = np.arange(1,10).reshape(3,3)
a_det = np.linalg.det(a)
print(a_det)

-9.51619735392994e-16


In [62]:
# it will give value of x and y from two equation
c = np.array([[1,1],[3,8]])
b = np.array([2200,10100])
r = np.linalg.solve(c,b)
print(r)

[1500.  700.]


In [63]:
help(np.linalg.solve)

Help on function solve in module numpy.linalg:

solve(a, b)
    Solve a linear matrix equation, or system of linear scalar equations.
    
    Computes the "exact" solution, `x`, of the well-determined, i.e., full
    rank, linear matrix equation `ax = b`.
    
    Parameters
    ----------
    a : (..., M, M) array_like
        Coefficient matrix.
    b : {(..., M,), (..., M, K)}, array_like
        Ordinate or "dependent variable" values.
    
    Returns
    -------
    x : {(..., M,), (..., M, K)} ndarray
        Solution to the system a x = b.  Returned shape is identical to `b`.
    
    Raises
    ------
    LinAlgError
        If `a` is singular or not square.
    
    See Also
    --------
    scipy.linalg.solve : Similar function in SciPy.
    
    Notes
    -----
    
    .. versionadded:: 1.8.0
    
    Broadcasting rules apply, see the `numpy.linalg` documentation for
    details.
    
    The solutions are computed using LAPACK routine ``_gesv``.
    
    `a` must be squa

In [66]:
# 2x - y = z = 10
# x + 2y -3z = 3
# 9x + y + 7z = 9
# find the value of x , y and z

a = np.array([[2, -1, 1],[1, 2, -3],[9, 1, 7]])
b = np.array([10, 3, 9])
result = np.linalg.solve(a,b)
print(result)

[ 3.98039216 -5.1372549  -3.09803922]


In [67]:
a = np.array([23,65,54,32,12,98,99])
print(np.min(a))
print(np.max(a))
print(np.average(a))

12
99
54.714285714285715


In [69]:
a  = np.array([[100,20,30],[10,50,60],[25,15,18],[4,5,19]])
print(a)
print(np.min(a))
print(np.min(a,axis=0))
print(np.min(a,axis=1))


[[100  20  30]
 [ 10  50  60]
 [ 25  15  18]
 [  4   5  19]]
4
[ 4  5 18]
[20 10 15  4]


In [70]:
a  = np.array([[100,20,30],[10,50,60],[25,15,18],[4,5,19]])
print(a)
print(np.max(a))
print(np.max(a,axis=0))
print(np.max(a,axis=1))

[[100  20  30]
 [ 10  50  60]
 [ 25  15  18]
 [  4   5  19]]
100
[100  50  60]
[100  60  25  19]


In [71]:
a  = np.array([[100,20,30],[10,50,60],[25,15,18],[4,5,19]])
print(a)
print(np.sum(a))
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))

[[100  20  30]
 [ 10  50  60]
 [ 25  15  18]
 [  4   5  19]]
356
[139  90 127]
[150 120  58  28]
