In [1]:
import numpy as np

In [6]:
a = np.arange(1,16)
print(a)
# print(np.split(a,4)) should be in equal division
print(np.split(a,5))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12]), array([13, 14, 15])]


In [8]:
a = np.arange(1,25).reshape(6,4)
print(a)

print(np.split(a,2))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]]), array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])]


In [11]:
a = np.arange(1,25).reshape(6,4)
print(a)

print(np.split(a,4,axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[array([[ 1],
       [ 5],
       [ 9],
       [13],
       [17],
       [21]]), array([[ 2],
       [ 6],
       [10],
       [14],
       [18],
       [22]]), array([[ 3],
       [ 7],
       [11],
       [15],
       [19],
       [23]]), array([[ 4],
       [ 8],
       [12],
       [16],
       [20],
       [24]])]


In [12]:
a = np.arange(10,101,10)
print(a)
print(np.split(a,[2,5,7])) # here 2,5,7 is index number 

[ 10  20  30  40  50  60  70  80  90 100]
[array([10, 20]), array([30, 40, 50]), array([60, 70]), array([ 80,  90, 100])]


In [17]:
a = np.arange(5,100,5)
print(a)
print(np.split(a,[5,10,15]))

[ 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[array([ 5, 10, 15, 20, 25]), array([30, 35, 40, 45, 50]), array([55, 60, 65, 70, 75]), array([80, 85, 90, 95])]


In [20]:
a = np.arange(1,13).reshape(2,6)
print(a)
result =np.split(a,[2,4,6],axis=1)
print(result[0])
print(result[1])
print(result[2])
print(result[3])
print(result)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[1 2]
 [7 8]]
[[ 3  4]
 [ 9 10]]
[[ 5  6]
 [11 12]]
[]
[array([[1, 2],
       [7, 8]]), array([[ 3,  4],
       [ 9, 10]]), array([[ 5,  6],
       [11, 12]]), array([], shape=(2, 0), dtype=int32)]


In [21]:
a = np.arange(1,13).reshape(2,6)
print(a)
result =np.split(a,[2,3,5],axis=1)
print(result[0])
print(result[1])
print(result[2])
print(result[3])
print(result)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[1 2]
 [7 8]]
[[3]
 [9]]
[[ 4  5]
 [10 11]]
[[ 6]
 [12]]
[array([[1, 2],
       [7, 8]]), array([[3],
       [9]]), array([[ 4,  5],
       [10, 11]]), array([[ 6],
       [12]])]


In [26]:
a = np.arange(1,13).reshape(4,3)
print(a)
result =np.vsplit(a,2)
print(result[0])
print(result[1])

print(result)

# row vise , 0 axis

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]


In [27]:
a = np.arange(1,13).reshape(2,6)
print(a)
result =np.hsplit(a,[2,4,6])
print(result[0])
print(result[1])
print(result[2])
print(result[3])
print(result)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[1 2]
 [7 8]]
[[ 3  4]
 [ 9 10]]
[[ 5  6]
 [11 12]]
[]
[array([[1, 2],
       [7, 8]]), array([[ 3,  4],
       [ 9, 10]]), array([[ 5,  6],
       [11, 12]]), array([], shape=(2, 0), dtype=int32)]


In [34]:
a = np.arange(1,13).reshape(2,2,3)
print(a)

result =np.dsplit(a,[1,2])
print(result[0])
# print(result[1])
# print(result[2])

print(result)
# 3d or more


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1]
  [ 4]]

 [[ 7]
  [10]]]


IndexError: list index out of range