In [24]:
import numpy as np
print(np.empty(3))

[2.12199579e-312 4.24399158e-314 8.48798317e-313]


In [25]:
arr = np.array([[1,2,3],[4,5,6]])
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]


In [26]:
a = np.array([[10,2],[1,0.5]])
b = np.array([2100,600])

result = np.linalg.solve(a,b)
print(result)

[ -50. 1300.]


In [27]:
a = np.array([[5,4],[3,5]])
b = np.array([200,200])

r = np.linalg.solve(a,b)
print(r)

[15.38461538 30.76923077]


In [36]:
a = np.array([[200,100,20],[1,2,3],[40,40,40]])
b = np.array([1400,50,1400])

r = np.linalg.solve(a,b)
print(r)

[-185.  425. -205.]


In [30]:
a = np.array([[100,50],[250,500]])
b = np.array([50,200])

sol = np.linalg.solve(a,b)
print(sol)

[0.4 0.2]


In [34]:
A = np.array([[4, 3, 2], [-2, 2, 3], [3, -5, 2]])
B = np.array([25, -10, -4])
X = np.linalg.solve(A,B)

print(X)

[ 5.  3. -2.]
